services:
  - type: web
    name: chatbot-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot_django.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_django.settings
      - key: PYTHON_VERSION
        value: 3.11
